# generated by datamodel-codegen:
#   filename:  project-generation.schema.json
#   timestamp: 2026-08-21T00:39:11+00:00

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AllPartitionDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Literal['all'] = Field(..., title='Mode')


class Mode(StrEnum):
    direct = 'direct'
    automatic = 'automatic'
    hybrid = 'hybrid'


class AllocationDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Mode = Field(..., title='Mode')
    strategy: str | None = Field(None, title='Strategy')
    reserve: list[str] | None = Field([], title='Reserve')
    ganging_policy: str | None = Field(None, title='Ganging Policy')


class BiasDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: str = Field(..., title='Mode')
    level: Any | None = Field(None, title='Level')


class DeviceStateRuleDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    when: dict[str, Any] = Field(..., title='When')
    set: dict[str, Any] = Field(..., title='Set')


class DimensionValueDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Any = Field(..., title='Value')
    set: dict[str, Any] | None = Field({}, title='Set')


class EachPartitionDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Literal['each'] = Field(..., title='Mode')


class ExplicitGroupDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    group_type: str = Field(..., title='Group Type')
    pins: list[str] = Field(..., title='Pins')
    parameters: dict[str, Any] | None = Field({}, title='Parameters')


class ExplicitTestGroupDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: str = Field(..., title='Group')
    stress_points: list[dict[str, Any]] = Field(..., title='Stress Points')


class ExplicitTestPlanDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    test_type: str = Field(..., title='Test Type')
    dimensions: dict[str, Any] | None = Field({}, title='Dimensions')
    device_state: str | None = Field(None, title='Device State')
    test_groups: list[ExplicitTestGroupDefinition] = Field(..., title='Test Groups')


class FormatterDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str = Field(..., title='Type')
    separator: str | None = Field(None, title='Separator')
    decimal_places: int | None = Field(None, title='Decimal Places')


class GroupByPartitionDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Literal['group_by'] = Field(..., title='Mode')
    fields: list[str] = Field(..., min_length=1, title='Fields')


class InlineSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['inline'] = Field('inline', title='Type')
    records: list[dict[str, Any]] = Field(..., title='Records')


class NameFieldDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(..., title='Source')
    mapping: str | None = Field(None, title='Mapping')
    formatter: str | None = Field(None, title='Formatter')
    when: dict[str, Any] | None = Field(None, title='When')


class NameTemplateDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    template: str = Field(..., title='Template')
    fields: dict[str, NameFieldDefinition] | None = Field(
        {}, title='Fields', validate_default=True
    )


class NamedSourceReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(..., title='Source')


class OverrideScope(StrEnum):
    plan = 'plan'
    group = 'group'


class PowerResourceDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str | None = Field(None, title='Role')
    parameters: dict[str, Any] | None = Field({}, title='Parameters')


class PowerSequenceTimingDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delay: float | None = Field(0.0, title='Delay')
    after: str | None = Field(None, title='After')


class ProjectMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, title='Name')
    source: str | None = Field(None, title='Source')
    metadata: dict[str, Any] | None = Field({}, title='Metadata')


class SelectionDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    where: dict[str, Any] | None = Field({}, title='Where')


class SourceFieldMapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str = Field(..., alias='from', title='From')
    mapping: str | None = Field(None, title='Mapping')
    formatter: str | None = Field(None, title='Formatter')


class TestGroupsDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    select: SelectionDefinition | None = Field({}, validate_default=True)
    partition: (
        EachPartitionDefinition | AllPartitionDefinition | GroupByPartitionDefinition
    ) = Field(..., discriminator='mode', title='Partition')


class TimingDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    power_on: PowerSequenceTimingDefinition | None = None
    power_off: PowerSequenceTimingDefinition | None = None


class Cast(Enum):
    float = 'float'
    int = 'int'
    str = 'str'
    bool = 'bool'


class ValueDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str | None = Field(None, alias='from')
    value: Any | None = None
    aggregate: str | None = None
    mapping: str | None = None
    formatter: str | None = None
    cast: Cast | None = None
    when: dict[str, Any] | None = Field(None, title='When')


class SetValueDefinition(
    RootModel[
        ValueDefinition
        | list[ValueDefinition]
        | str
        | int
        | float
        | bool
        | dict[str, Any]
        | list[Any]
        | None
    ]
):
    root: (
        ValueDefinition
        | list[ValueDefinition]
        | str
        | int
        | float
        | bool
        | dict[str, Any]
        | list[Any]
        | None
    ) = Field(..., title='SetValueDefinition')


class HardwareDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(..., title='Source')


class GroupByFieldDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(..., title='Source')
    when: dict[str, Any] | None = Field(None, title='When')


class CsvSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['csv'] = Field('csv', title='Type')
    path: str = Field(..., title='Path')
    mapping: dict[str, str | SourceFieldMapping] | None = Field(
        {}, title='Mapping', validate_default=True
    )


class DimensionDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    values: list[DimensionValueDefinition | str | int | float | bool | None] = (
        Field(..., min_length=1, title='Values')
    )


class ExcelSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['excel'] = Field('excel', title='Type')
    path: str = Field(..., title='Path')
    sheet: str | int | None = Field(None, title='Sheet')
    mapping: dict[str, str | SourceFieldMapping] | None = Field(
        {}, title='Mapping', validate_default=True
    )


class GroupGenerationRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    select: SelectionDefinition | None = Field({}, validate_default=True)
    group_by: list[str | GroupByFieldDefinition] = Field(..., title='Group By')
    set: dict[str, SetValueDefinition | None] | None = Field(
        {}, title='Set', validate_default=True
    )
    name: NameTemplateDefinition


class GroupsDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    external: bool | None = Field(False, title='External')
    explicit: list[ExplicitGroupDefinition] | None = Field(
        [], title='Explicit', validate_default=True
    )
    generation: list[GroupGenerationRule] | None = Field(
        [], title='Generation', validate_default=True
    )


class JsonSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['json'] = Field('json', title='Type')
    path: str = Field(..., title='Path')
    select: str | None = Field(None, title='Select')
    mapping: dict[str, str | SourceFieldMapping] | None = Field(
        {}, title='Mapping', validate_default=True
    )


class OverrideDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scope: OverrideScope | None = 'plan'
    when: dict[str, Any] = Field(..., title='When')
    set: dict[str, Any] | None = Field({}, title='Set')
    exclude: bool | None = Field(False, title='Exclude')


class PowerDomainDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    groups: list[str] = Field(..., title='Groups')
    assignment: str = Field(..., title='Assignment')
    bias: BiasDefinition
    timing: TimingDefinition | None = None


class TestPlanRuleDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    groups: TestGroupsDefinition
    dimensions: list[DimensionDefinition] | None = Field(
        [], title='Dimensions', validate_default=True
    )
    template: dict[str, Any] = Field(..., title='Template')
    overrides: list[OverrideDefinition] | None = Field(
        [], title='Overrides', validate_default=True
    )


class DeviceStateDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extends: str | None = Field(None, title='Extends')
    power_domains: list[PowerDomainDefinition] | None = Field(
        [], title='Power Domains', validate_default=True
    )
    allocation: AllocationDefinition | None = None
    rules: list[DeviceStateRuleDefinition] | None = Field(
        [], title='Rules', validate_default=True
    )


class InlineSourceReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: InlineSource | JsonSource | CsvSource | ExcelSource = Field(
        ..., discriminator='type', title='Source'
    )


class TestPlanGenerationDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rules: list[TestPlanRuleDefinition] | None = Field(
        [], title='Rules', validate_default=True
    )


class DutDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | ValueDefinition | NameTemplateDefinition = Field(..., title='Name')
    pins: NamedSourceReference | InlineSourceReference = Field(..., title='Pins')


class ProjectGenerationDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: str = Field(..., title='Schema Version')
    project: ProjectMetadata
    constants: dict[str, Any] | None = Field({}, title='Constants')
    mappings: dict[str, dict[str, Any]] | None = Field({}, title='Mappings')
    formatters: dict[str, FormatterDefinition] | None = Field(
        {}, title='Formatters', validate_default=True
    )
    sources: dict[str, InlineSource | JsonSource | CsvSource | ExcelSource] | None = (
        Field({}, title='Sources', validate_default=True)
    )
    dut: DutDefinition | None = None
    groups: GroupsDefinition | None = Field({}, validate_default=True)
    hardware: HardwareDefinition | None = None
    power_resources: dict[str, PowerResourceDefinition] | None = Field(
        {}, title='Power Resources', validate_default=True
    )
    device_states: dict[str, DeviceStateDefinition] | None = Field(
        {}, title='Device States', validate_default=True
    )
    test_plans: list[ExplicitTestPlanDefinition] | None = Field(
        [], title='Test Plans', validate_default=True
    )
    test_plan_generation: TestPlanGenerationDefinition | None = Field(
        {}, validate_default=True
    )
    output: dict[str, Any] | None = Field({}, title='Output')
